#!/bin/bash

#TODO : apt-get install pm-utils and change acpi button behaviour by auto adding sleep.sh containing pm-suspend (done on elianecomputer)
#TODO : may have to sed in /network/interface to eliminate eventual previous config of eth0 and co, otherwise network manager wont work
#TODO : replace "main" with "main contrib non-free" in apt/source.list
#TODO : check audio, sometimes headset doesnt work well

PACKAGES=$1

INSTALLATION=".installation"
WINATEFOLDER="WinAte-master"
WINATESCRIPT="install.sh"
THISSCRIPT="tca-install"

if [ `whoami` == "root" ]; then
 
	#Optional
	OPTIONAL="gdebi vlc gimp libreoffice libreoffice-gtk git lxterminal thunderbird chromium firefox-esr wicd wicd-gtk hplip-gui xfce4-power-manager $PACKAGES"
	if echo $PACKAGES|grep windows > /dev/null 2>&1; then
		echo "windows can't be installed as root. Wait for the next part of installation (user side)"
	fi

	FRENCHTRAD="mythes-fr libreoffice-help-fr libreoffice-l10n-fr hunspell-fr hunspell-fr-modern hyphen-fr"
	FRENCHHELP="doc-linux-fr-pdf debian-faq-fr doc-linux-fr-text manpages-fr"
	
	#Python-pip
	apt-get install python-pip python3-pip
	
	#Search
	#More here : https://www.lesbonscomptes.com/recoll/filters/filters.html
	apt-get install -y recoll
	apt-get install -y python-libxml2 python-libxslt1
	pip install pylzma
	pip3 install pylzma
	pip install epub
	pip3 install epub
	pip install rarfile
	pip3 install rarfile
	rm /usr/share/recoll/examples/mimeconf && rm /usr/share/recoll/examples/mimeview && rm /usr/share/recoll/examples/mimemap
	cd /usr/share/recoll/examples
	wget https://raw.githubusercontent.com/agencetca/custom-debian-script/master/recoll/mimeconf
	echo "application/pdf = execm rclmpdf" >> mimeconf
	echo "application/vnd.ms-powerpoint = exec rclppt" >> mimeconf
	echo "application/x-tar = execm rcltar" >> mimeconf
	wget https://raw.githubusercontent.com/agencetca/custom-debian-script/master/recoll/mimeview
	wget https://raw.githubusercontent.com/agencetca/custom-debian-script/master/recoll/mimemap
	cd /usr/share/recoll/filters
	rm rclxml 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclxml
	chmod +x rclxml
	rm rclpdf 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclpdf
	chmod +x rclpdf
	rm rclscribus 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclscribus
	chmod +x rclscribus
	rm rcl7z 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rcl7z
	chmod +x rcl7z
	rm rclmpdf 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclmpdf
	chmod +x rclmpdf
	rm rclsoff 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclsoff
	chmod +x rclsoff
	rm rclpurple 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclpurple
	chmod +x rclpurple
	rm rclppt 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclppt
	chmod +x rclppt
	rm ppt-dump.py 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/ppt-dump.py
	chmod +x ppt-dump.py
	rm msodump.zip 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/msodump.zip
	rm rclepub 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclepub
	chmod +x rclepub
	rm rclchm 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclchm
	chmod +x rclchm
	rm rcltar 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rcltar
	chmod +x rcltar
	rm rcldia 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rcldia
	chmod +x rcldia
	rm rclokulnote 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclokulnote
	chmod +x rclokulnote
	rm rclrar 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclrar
	chmod +x rclrar
	rm rclzip 2> /dev/null
	wget https://github.com/agencetca/custom-debian-script/blob/master/recoll/rclzip
	chmod +x rclzip
	cd
	
	#Wifi
	apt-get install -y firmware-iwlwifi firmware-realtek

	#Core
	apt-get install -y sudo default-jre ntp wget zip unzip vim openssh-server glances clipit gedit evince scrot shutter xarchiver alsamixergui preload wine cups printer-drivers* talkd talk numlockx $OPTIONAL &&
	
	#Resolve some bugs
	apt-get install -y libcanberra-gtk-module libcanberra-gtk3-module
	
	#Install Skype 64 bits
	wget https://go.skype.com/skypeforlinux-64.deb && sudo gdebi --n skypeforlinux-64.deb
	rm skypeforlinux-64.deb
	
	#Install dropbox 64 bits (might not be the latest)
	wget https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb && sudo gdebi --n dropbox_2019.02.14_amd64.deb
	rm dropbox_2019.02.14_amd64.deb
	
	touch /etc/modprobe.d/blacklist.conf
	if ! grep -q pcspkr /etc/modprobe.d/blacklist.conf; then
		echo "blacklist pcspkr" >> /etc/modprobe.d/blacklist.conf
	fi

	GRUBCURRENT=$(perl -ne 'print $1 if /.*GRUB_TIMEOUT=(.*).*/' /etc/default/grub)
	if [ ! $GRUBCURRENT == 0 ]; then
		sed -i "s/\(GRUB_TIMEOUT*= *\).*/\11/" /etc/default/grub &&
		update-grub
	fi
	
	echo -e "Which user you'll use?"
	read USER

	if ! grep -q "%sudo" /etc/sudoers; then
		
		groupadd -f sudo &&
		echo "" >> /etc/sudoers &&
		echo "# Allow members of group sudo to execute any command" >> /etc/sudoers &&
		echo "%sudo   ALL=(ALL:ALL) ALL" >> /etc/sudoers &&
		usermod -a $USER -G sudo
	fi

	CURRENT_LOC=`pwd` &&
	
	if [ ! -d /home/$USER/$INSTALLATION ]; then
		mkdir /home/$USER/$INSTALLATION
	fi

	cp $CURRENT_LOC/$THISSCRIPT /home/$USER/$INSTALLATION
	chown -R $USER:$USER /home/$USER/$INSTALLATION
	echo -e "Everything is fine. Please exec cd ~/$INSTALLATION && ./$THISSCRIPT [windows]"
	exec su -l $USER
	exit 0
fi

if [ ! -d ~/HELP ]; then
	mkdir ~/HELP &&
	wget -P ~/HELP ftp://ftp.linux-france.org/pub/article/cesar/Survie_Linux.pdf.gz &&
	gunzip ~/HELP/Survie_Linux.pdf.gz &&
	ln -s /usr/share/doc/HOWTO ~/HELP/HOWTO &&
	sudo gunzip -r ~/HELP/HOWTO/ &&
	ln -s /usr/share/doc/debian/FAQ ~/HELP/FAQ &&
	sudo gunzip -r ~/HELP/FAQ/
fi

PROGRAMFOLD="Programs"

if [ ! -d ~/$PROGRAMFOLD ]; then
	mkdir ~/$PROGRAMFOLD
fi

if ! echo $PATH|grep ":/home/$USER/$PROGRAMFOLD" > /dev/null 2>&1; then
	grep -v "PATH" ~/.bashrc > .bashrc
	echo -e "export PATH=$PATH:/home/$USER/$PROGRAMFOLD" >> .bashrc &&
	mv .bashrc ~/.bashrc &&
	export PATH=$PATH:/home/$USER/$PROGRAMFOLD
fi

if [ ! -z $PACKAGES ]; then
	sudo apt-get install -y $PACKAGES
fi

if [ -L /home/$USER/$PROGRAMFOLD/$THISSCRIPT ]; then
	rm -f /home/$USER/$PROGRAMFOLD/$THISSCRIPT
fi
ln -s ~/$INSTALLATION/$THISSCRIPT /home/$USER/$PROGRAMFOLD/$THISSCRIPT

sudo chown -R $USER:$USER ~ &&

if echo $PACKAGES|grep windows > /dev/null 2>&1; then
	if [ ! -d ~/$INSTALLATION/$WINATEFOLDER ]; then
		echo "Windows template is being installed..."
		sudo apt-get install -y lxde-core lxpanel lxsession lightdm pcmanfm compton openbox &&

		read -p "Autologin? " -n 1 -r
		echo    # (optional) move to a new line
		if [[ $REPLY =~ ^[Yy]$ ]]
		then
		   sudo sed -i '/autologin-user=/c\autologin-user='$USER /etc/lightdm/lightdm.conf
		else
		   sudo sed -i '/autologin-user=/c\#autologin-user=' /etc/lightdm/lightdm.conf
		fi

		read -p "Autolock numpad? " -n 1 -r
		echo    # (optional) move to a new line
		if [[ $REPLY =~ ^[Yy]$ ]]
		then
			NUMLOCK=$(which numlockx)
			echo "greeter-setup-script=$NUMLOCK on" | sudo tee --append /etc/lightdm/lightdm.conf
			#echo "numlockx &" >> ~/.config/openbox/autostart
		fi

		cd ~/$INSTALLATION &&
		wget http://github.com/nhermosilla14/WinAte/archive/master.zip &&
		unzip master.zip &&
		rm master.zip &&
		cd $WINATEFOLDER &&
		bash $WINATESCRIPT &&	
		cd ~/$INSTALLATION &&
		rm -rf $WINATEFOLDER &&
		if grep scrot ~/.config/openbox/lxde-rc.xml > /dev/null 2>&1; then
			sed -i 's/scrot/shutter -f/g' ~/.config/openbox/lxde-rc.xml
		fi
		echo "Done"
		echo "Computer is going to reboot in 5 secondes"
		sleep 5
		sudo reboot
		exit 0
	fi
fi

#CONTINUE ONLY IF WINDOWS-LIGHTDM HAS NOT BEEN (RE)INSTALLED

#NUMLOCK FOR GDM3
if [ -f /etc/gdm3/Init/Default ]; then
	echo "
	  if [ -x /usr/bin/numlockx ] ; then
	  /usr/bin/numlockx on
	  fi
	" >> /etc/gdm3/Init/Default
fi

sleep 1 &&
echo "done" &&
exit 0
